# https://hub.docker.com/r/chatwoot/chatwoot/tags
FROM iditelesom/chatwoot:update_4.0.4_dev

RUN apk add --no-cache multirun postgresql-client

COPY --chmod=755 start.sh ./

ENTRYPOINT ["/bin/sh"]

CMD ["start.sh"]
